import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LanguageButton from "./components/LanguageButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased text-black bg-transparent  m-0 p-0` }>
        {/* Overlay Language Button */}
        <div className="fixed top-4 right-4 z-50 ">
          <LanguageButton />
        </div>

        {/* Main Page Content */}
        {children}
      </body>
    </html>
  );
}
